### ISSUE TITLE
Unable to send funds v0.3.2 (testnet4)

### ISSUE THREAD

**Issue by mstrewe** [iotaledger/cli-wallet#47]
Expected behavior:

transfer should success

Actual behavior:

transfer fails with Insufficient funds error

![image](https://user-images.githubusercontent.com/15155589/107032472-2a83ff80-67b4-11eb-908e-c6903c5c8723.png)

cli-wallet version:
0.3.2

node:
my chrysalis node which is synched and healthy running testnet4

steps:

- created wallet 
- receive funds from faucet (https://explorer.iota.org/chrysalis/message/78918b190f92c07ffbb10367e5ff669d18728d0da6ada6aea830fa2cfb5516c1)
- sync wallet
- try to transfer

**Comment by Thoralf-M** [comment]
Was this your own address? Then it could be the case that it doesn't work, because if the input address is used as output there can't be a remainder to the same address, because that would require two outputs to the same address in a single transaction which is not allowed by the protocol
There should also be a new error message with the latest version
